#!/bin/bash
#
# Copy sources and specs to rpmbuild directory and start to build

mv *.tar.gz ~/rpmbuild/SOURCES/
mv *.zip ~/rpmbuild/SOURCES/

cp *.spec ~/rpmbuild/SPECS/

for spec in $(ls *.spec)
do
    echo $spec
    rpmbuild -ba ~/rpmbuild/SPECS/$spec
done
